package me.gulya.wrenflow

/**
 * Bridge to wrenflow-core Rust library via UniFFI-generated bindings.
 *
 * The UniFFI Kotlin bindings will be generated by `uniffi-bindgen-kotlin`
 * and placed in this package. For now, this is a placeholder that loads
 * the native library and exposes a test function.
 */
object RustBridge {
    init {
        System.loadLibrary("wrenflow_ffi")
    }

    /** Call Rust `default_config()` via JNI — returns JSON string */
    external fun defaultConfig(): String

    /** Call Rust `pipeline_status_text()` via JNI */
    external fun pipelineStatusText(state: String): String
}
